[colors.bright]
black = "#808080"
blue = "#0066ff"
cyan = "#00ffff"
green = "#33ff00"
magenta = "#cc00ff"
red = "#fe0100"
white = "#FFFFFF"
yellow = "#feff00"

[colors.cursor]
cursor = "#ffffff"
text = "#F81CE5"

[colors.normal]
black = "#000000"
blue = "#0066ff"
cyan = "#00ffff"
green = "#33ff00"
magenta = "#cc00ff"
red = "#fe0100"
white = "#d0d0d0"
yellow = "#feff00"

[colors.primary]
background = "#212328"
foreground = "#ffffff"

[font]
size = 13

[font.normal]
# family = "CaskaydiaMonoNerdFont"
family = "JetBrainsMonoNerdFont"
style = "SemiBold"

[window]
opacity = 1

[window.padding]
x = 10
y = 10
