theme = "dark_plus"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"
# bufferline = "always"
idle-timeout = 50
auto-format = true
auto-pairs = false
gutters = ["diagnostics", "spacer",  "diff"]

[editor.statusline]
left = ["mode", "separator", "version-control"]
center = [
  "register",
  "spacer",
  "file-modification-indicator",
  "spacer",
  "spinner",
  "file-name",
]
right = [
  "diagnostics",
  "spacer",
  "file-encoding",
  "file-type",
  "spacer",
  "selections",
  "position",
  "total-line-numbers",
]
separator = "  " # " ▓    ║  "
mode.normal = "NORMAL 󰹂"
mode.insert = "INSERT 󰏪"
mode.select = "SELECT 󱊅"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
C-o = ":config-open"
C-r = ":config-reload"

C-h = "select_prev_sibling"
C-j = "shrink_selection"
C-k = "expand_selection"
C-l = "select_next_sibling"

C-e = ["goto_line_end"]
C-q = ["goto_line_start"]
esc = ["collapse_selection", "keep_primary_selection"]

C-s = [":write!"]
C-z = ["undo"]
C-Z = ["redo"]

# Muscle memory
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
0 = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
G = "goto_file_end"
"%" = "match_brackets"
V = ["select_mode", "extend_to_line_bounds"]
C = ["extend_to_line_end", "yank_main_selection_to_clipboard", "delete_selection", "insert_mode"]
S = "surround_add"

p = ["paste_clipboard_after", "collapse_selection"]
P = ["paste_clipboard_before", "collapse_selection"]

del = ["delete_selection"]

[keys.insert]

